---

- name: "IVM | Clone/Update"
  git:
    repo: "{{ ivm_repo }}"
    dest: "~/.ivm"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false
  changed_when: false

- name: "IVM | Linking"
  file:
    src: "~/.ivm/bin/ivm"
    dest: "{{ nvm_symlink_dir }}/ivm"
    state: link
    force: yes
  changed_when: false

- name: "IVM | Ensure shell profiles are configured"
  lineinfile:
    dest: "~/{{ item.item.item }}"
    regexp: 'export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist'
    line:  'export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist;'
    state: present
  with_items:
    - "{{ available_shell_profiles.results }}"
  when: item.item.stat.exists|bool == true