---
# Tasks file for NodeJS

- name: "NodeJS | Check"
  shell: "{{ nvm_symlink_dir }}/nvm ls | cat"
  register: installed_nodejs_versions
  changed_when: false

- name: "NodeJS | Install all requested versions"
  shell: "{{ nvm_symlink_dir }}/nvm install {{ item }}"
  changed_when: false
  with_items:
  - "{{ node_version }}"
  - "{{ node_versions }}"

- name: "NodeJS | Switching"
  shell: "{{ nvm_symlink_dir }}/nvm use --delete-prefix {{ node_version }}"
  register: fubarhouse_npm_switch
  changed_when: false
  when: 'node_version in nodejs_available_versions.stdout'

- name: "NodeJS | Linking"
  shell: "{{ nvm_symlink_dir }}/nvm alias default {{ node_version }}"
  changed_when: false
  when: 'node_version in nodejs_available_versions.stdout'

- name: "NodeJS | Import exports"
  lineinfile:
    dest: "~/{{ item.item.item }}"
    line: "export PATH=$PATH:$(npm config --global get prefix)/bin"
    state: present
  with_items:
    - "{{ available_shell_profiles.results }}"
  when: item.item.stat.exists|bool == true

- name: "NodeJS | Verify version in use"
  shell: ". ~/{{ item.item.item }} && node -v"
  register: node_current_version
  changed_when: false
  failed_when: 'node_current_version.stdout.find(node_version) == -1'
  with_items:
    - "{{ available_shell_profiles.results }}"
  when:
    - 'item.item.stat.exists|bool == true'
