---
# Tasks file for NVM

- name: "NVM | Looking at shell profiles"
  stat:
    path: "{{ item }}"
  register: available_shell_profiles
  with_items:
  - "{{ shell_profiles }}"

- name: "NVM | Clean-up"
  file:
    path: "{{ nvm_install_dir }}"
    state: absent
  when: nodejs_clean_install|bool == true

- name: NVM | Clean-up default version from shell profiles
  lineinfile:
    dest: "~/{{ item }}"
    regexp: '.nvm/v{{ node_version }}/bin'
    line:  'export PATH=$PATH:{{ nvm_install_dir }}/v{{ node_version }}/bin;'
    state: absent
  with_items:
    - "{{ available_shell_profiles.results }}"
  ignore_errors: yes
  when: item.stat.exists|bool == true

- name: NVM | Clean-up other versions from shell profiles
  lineinfile:
    dest: "~/{{ item[0].item }}"
    regexp: '.nvm/v{{ item[1] }}/bin'
    line:  'export PATH=$PATH:{{ nvm_install_dir }}/v{{ item[1] }}/bin;'
    state: absent
  with_nested:
    - "{{ available_shell_profiles.results }}"
    - "{{ node_versions }}"
  ignore_errors: yes
  when:
  - nodejs_clean_install|bool == true
  - item[0].stat.exists|bool == true

- name: "NodeJS | Remove imported exports not associated to specific versions"
  lineinfile:
    dest: "~/{{ item.item }}"
    line: "export PATH=$PATH:$(npm config --global get prefix)/bin"
    state: absent
  with_items: "{{ available_shell_profiles.stdout }}"
  when:
  - available_shell_profiles.stdout is defined
  - nodejs_clean_install|bool == true
  - item.stat.exists|bool == true

- name: "NVM | Check"
  stat:
    path: "{{ nvm_install_dir }}"
  register: fubarhouse_npm_nvm_installed

- name: "NVM | Get distribution"
  get_url:
    url: "https://github.com/creationix/nvm/archive/v{{ nvm_version }}.tar.gz"
    dest: "/tmp/{{ nvm_version }}.tar.gz"
  when:
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Create temporary extraction directory"
  file:
    state: directory
    mode: 0777
    path: "/tmp/nvm-{{ nvm_version }}"
  when:
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Create pernament extraction directory"
  file:
    state: directory
    mode: 0777
    path: "{{ nvm_install_dir }}"
  when:
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Unpack distribution"
  unarchive:
    src: "/tmp/{{ nvm_version }}.tar.gz"
    dest: "/tmp/nvm-{{ nvm_version }}"
    copy: "no"
  when:
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Moving to installation directory"
  synchronize:
    src: "/tmp/nvm-{{ nvm_version }}/nvm-{{ nvm_version }}"
    dest: "{{ nvm_install_dir }}"
    delete: yes
    recursive: yes
  when:
    - ansible_ssh_user is undefined
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Moving to installation directory"
  shell: "cp -rf /tmp/nvm-{{ nvm_version }}/nvm-{{ nvm_version }}/* {{ nvm_install_dir }}/"
  when:
    - ansible_ssh_user is defined
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Remove temporary data"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/tmp/{{ nvm_version }}.tar.gz"
  - "/tmp/nvm-{{ nvm_version }}"
  when:
    - fubarhouse_npm_nvm_installed.stat.exists|bool == false
    - install_nvm_git|bool == false

- name: "NVM | Clone"
  git:
    repo: "https://github.com/creationix/nvm.git"
    dest: "{{ nvm_install_dir }}"
    clone: yes
    update: no
    version: "{{ nvm_version }}"
  when: install_nvm_git|bool == true

- name: "NVM | Fetch"
  shell: "cd {{ nvm_install_dir }} && git fetch --tags origin"
  when: install_nvm_git|bool == true and fubarhouse_npm_nvm_installed.stat.exists|bool == false

- name: "NVM | Install"
  shell: "{{ nvm_install_dir }}/install.sh"
  when: fubarhouse_npm_nvm_installed.stat.exists|bool == false

- name: "NVM | Create an executable"
  template:
    src: "nvm.sh"
    dest: "{{ nvm_symlink_dir }}/nvm"
    mode: 0755

- name: "NVM | Get versions"
  shell: "{{ nvm_symlink_dir }}/nvm ls-remote"
  register: nodejs_available_versions
  changed_when: false

- name: NVM | Ensure shell profiles are available
  stat:
    path: "~/{{ item }}"
  register: available_shell_profiles
  with_items: "{{ available_shell_profiles.results }}"
  failed_when: false

- name: NVM | Ensure shell profiles are configured
  lineinfile:
    dest: "~/{{ item[0].item.item }}"
    regexp: "{{ item[1] }}"
    line:  "{{ item[1] }}"
    state: present
  with_nested:
    - "{{ available_shell_profiles.results }}"
    - "{{ nvm_shell_exports }}"
  when:
    - item[0].item.stat.exists|bool == true
