---

- name: "NodeJS | Install dependencies (CentOS)"
  become: yes
  become_user: root
  yum:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: present
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution == "CentOS" or ansible_distribution == "Amazon")

- name: "NodeJS | Install dependencies (Debian)"
  become: yes
  become_user: root
  apt:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: present
  when: ansible_os_family == "Debian"

- name: "NodeJS | Install dependencies (RedHat)"
  become: yes
  become_user: root
  dnf:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: present
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution != "CentOS" and ansible_distribution != "Amazon")
